version: "3"

services:

  web:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  #web:
  #  build:
  #    context: ./docker/apache
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./:/var/www
  #    - ./docker/apache/httpd.conf:/usr/local/apache2/conf.d/httpd.conf
  #  networks:
  #    - backend

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend

  node:
    build:
      context: ./docker/node
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    networks:
      - backend
    tty: true

  db:
    build:
      context: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  data:

networks:
  backend:
